### ISSUE TITLE
Cannot Start New Game

### ISSUE THREAD

**Issue by Johnkurveen** [seansegal/tincisnotcatan#8]
Each time I try making a new game, when I press start game, it kicks me back to the username menu. Using Chrome, and the same issue existed on Microsoft edge and for my friend, though her browser, Brave, seemed to work

**Comment by seansegal** [comment]
Thanks for opening the issue, I've noticed this too! **As a bad workaround, I was able to get it the game to work as expected on Safari with a Mac**. I think there must be some browser change that broke our code recently but haven't had time to look into it 😢 . Would love any help with the issue!

**Comment by reederda** [comment]
I'm noticing Firefox reports `Firefox can’t establish a connection to the server at wss://<LOCAL_IP_ADDRESS>:4567/groups/.` in the console. Could this be related? Fails to connect and so it reverts to the start page?

**Comment by DomenicTroilo** [comment]
Would live to see this fixed as well

**Comment by reederda** [comment]
@seansegal The problem appears to be occurring in src/main/resources/static/js/websocket.js with the declaration of the WebSocket. I found that if I replaced the _if_ statement with just `webSocket = new WebSocket("ws://" + location.hostname + ":" + location.port +  "/action/");` the issue is resolved.

**Comment by seansegal** [comment]
@reederda Thanks for the suggestion - I tried that in https://github.com/seansegal/tincisnotcatan/pull/9, but it has not resolved the issue for me.

**Comment by paga2004** [comment]
@reederda I had the same issue. It turned out that I had the wrong nginx config and didn't account for websocket in my redirect. Take a look at this: https://stackoverflow.com/questions/12102110/nginx-to-reverse-proxy-websockets-and-enable-ssl-wss
